# Generated by Django 4.2.8 on 2024-01-09 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(blank=True, max_length=255, null=True)),
                ('element', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.CharField(blank=True, max_length=255, null=True)),
                ('data_s', models.CharField(blank=True, max_length=255, null=True)),
                ('data_r', models.CharField(blank=True, max_length=255, null=True)),
                ('data_d', models.CharField(blank=True, max_length=255, null=True)),
                ('principle', models.CharField(blank=True, max_length=255, null=True)),
                ('seg', models.CharField(blank=True, max_length=255, null=True)),
                ('rir', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GymActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscule_group', models.CharField(blank=True, max_length=255, null=True)),
                ('nestedArray', models.ManyToManyField(to='fitness.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_days', models.CharField(blank=True, max_length=255, null=True)),
                ('gym_activities', models.ManyToManyField(to='fitness.gymactivity')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
