# Generated by Django 3.2.22 on 2023-11-06 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_auto_20231106_2135'),
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=255)),
                ('subSector', models.CharField(max_length=255)),
                ('elementD', models.CharField(blank=True, max_length=255, null=True)),
                ('data_s', models.IntegerField()),
                ('data_r', models.IntegerField()),
                ('data_d', models.CharField(max_length=255)),
                ('beginning', models.CharField(max_length=255)),
                ('data_sec', models.CharField(max_length=255)),
                ('data_rir', models.CharField(max_length=255)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Auth.membership')),
            ],
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
