# Generated by Django 3.2.22 on 2023-11-07 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0008_auto_20231107_0809'),
        ('fitness', '0003_alter_exercise_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Auth.membership'),
        ),
    ]
