# Generated by Django 3.2.22 on 2023-10-31 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
