# Generated by Django 3.2.22 on 2023-11-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_auto_20231106_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='objective',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
