# Generated by Django 3.2.22 on 2023-11-07 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_alter_user_objective'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='Reference',
        ),
    ]
