# Generated by Django 3.2.22 on 2023-11-07 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0007_remove_membership_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='SelectTrainer',
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
