# Generated by Django 3.2.22 on 2023-11-07 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0008_auto_20231107_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='DueDate',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='SelectMembershipplan',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='paymentStatus',
        ),
        migrations.DeleteModel(
            name='MembershipPlan',
        ),
    ]
