# Generated by Django 3.2.22 on 2023-11-07 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_alter_exercise_member'),
        ('Auth', '0009_auto_20231107_0814'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
