# Generated by Django 3.2.22 on 2023-11-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0011_alter_user_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='factor',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
